image: debian

stages:
  - build
  - test
  - memcheck

.install-utils: &install-utils
    apt update -yqq && apt install -yqq gcc make libreadline-dev &> /dev/null

build:
  stage: build
  before_script:
    - *install-utils
  script:
    - make
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: push
    paths:
      - build/src/server/*.o
      - build/src/client/*.o
      - server
      - client

test:
  stage: test
  before_script:
    - *install-utils
  script:
    - make test
    - tests/test_megaphone
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: pull-push
    paths:
      - build/src/server/*.o
      - build/src/client/*.o
      - build/test/*.o
      - test/test_megaphone


memcheck-test:
  stage: memcheck
  before_script:
    - *install-utils
    - apt update -yqq && apt install -yqq valgrind
  script:
    - apt-get update -qq && apt-get install -y -qq valgrind &> /dev/null
    - make test
    - valgrind --trace-children=yes --leak-check=full --error-exitcode=1 tests/test_megaphone
  allow_failure: true
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: pull
    paths:
      - build/src/server/.o*
      - build/src/client/.o*
      - build/test/.o*
      - test/test_megaphone

